import type { Entry } from '../types';

export const sampleEntries: Omit<Entry, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    workName: '原神',
    cpName: '散枫',
    type: '同人文',
    link: 'https://example.com/sanfeng1',
    author: '风见幽香',
    status: '已完结',
    tags: ['甜', 'HE'],
    readStatus: '已读',
    notes: '超级甜！！两个人的互动太可爱了，散兵的傲娇描写得刚刚好。',
    favorite: true,
  },
  {
    workName: '原神',
    cpName: '海维',
    type: '同人漫',
    link: 'https://example.com/haiwei1',
    author: '椰椰奶冻',
    status: '连载中',
    tags: ['中等', 'HE'],
    readStatus: '在读',
    notes: '学院日常向，小情侣拌嘴日常百看不厌~',
    favorite: true,
  },
  {
    workName: '原神',
    cpName: '散枫',
    type: '同人漫',
    link: 'https://example.com/sanfeng2',
    author: '秋秋',
    status: '已完结',
    tags: ['虐', 'BE'],
    readStatus: '已读',
    notes: '呜呜呜我的心好痛，但是写得太好了，BE美学天花板。',
    favorite: false,
  },
  {
    workName: '流浪地球2',
    cpName: '图恒宇×马兆',
    type: '同人文',
    link: 'https://example.com/tumazhao1',
    author: '数字生命卡',
    status: '已完结',
    tags: ['中等', 'OE'],
    readStatus: '已读',
    notes: '科幻感拉满，关于数字生命的探讨很有深度。',
    favorite: true,
  },
  {
    workName: '原神',
    cpName: '知妙',
    type: '视频',
    link: 'https://example.com/zhimiao1',
    author: '剪辑小白',
    status: '已完结',
    tags: ['甜', 'HE'],
    readStatus: '未读',
    notes: 'B站看到的剪辑，配乐超棒！',
    favorite: false,
  },
  {
    workName: '原神',
    cpName: '海维',
    type: '同人文',
    link: 'https://example.com/haiwei2',
    author: '卡维的画板',
    status: '连载中',
    tags: ['甜', '清水', 'HE'],
    readStatus: '在读',
    notes: '长篇连载，追更中！剧情很棒，感情线细腻。',
    favorite: true,
  },
  {
    workName: '明日方舟',
    cpName: '博傀',
    type: '同人文',
    link: '',
    author: '深海色',
    status: '暂停',
    tags: ['虐', '中等'],
    readStatus: '未读',
    notes: '收藏了很久还没看，据说很刀...',
    favorite: false,
  },
  {
    workName: '原神',
    cpName: '知妙',
    type: '图',
    link: 'https://example.com/zhimiao2',
    author: '某某画师',
    status: '已完结',
    tags: ['甜', '清水'],
    readStatus: '已读',
    notes: '太太画的知妙太可爱了！两个人贴贴的样子好幸福~',
    favorite: true,
  },
  {
    workName: '原神',
    cpName: '散枫',
    type: '音频',
    link: '',
    author: '配音社',
    status: '已完结',
    tags: ['甜'],
    readStatus: '未读',
    notes: '同人广播剧，据说配得超好。',
    favorite: false,
  },
  {
    workName: '流浪地球2',
    cpName: '图恒宇×马兆',
    type: '同人漫',
    link: 'https://example.com/tumazhao2',
    author: '机械臂',
    status: '已完结',
    tags: ['车'],
    readStatus: '弃坑',
    notes: '画风不太对我的审美...',
    favorite: false,
  },
  {
    workName: '原神',
    cpName: '公钟',
    type: '同人文',
    link: 'https://example.com/gongzhong1',
    author: '往生堂客卿',
    status: '已完结',
    tags: ['甜', 'HE', '车'],
    readStatus: '已读',
    notes: '经典老番了，但是每次看都很喜欢！',
    favorite: true,
  },
  {
    workName: '原神',
    cpName: '公钟',
    type: '其他',
    link: '',
    author: '匿名',
    status: '坑',
    tags: ['中等'],
    readStatus: '弃坑',
    notes: '作者坑了...可惜了这么好的设定。',
    favorite: false,
  },
];

export const loadSampleDataIfEmpty = (
  addEntry: (entry: Omit<Entry, 'id' | 'createdAt' | 'updatedAt'>) => void,
  entriesLength: number
) => {
  if (entriesLength === 0 && typeof window !== 'undefined') {
    const hasLoaded = localStorage.getItem('cp-grain-sample-loaded');
    if (!hasLoaded) {
      sampleEntries.forEach((entry) => addEntry(entry));
      localStorage.setItem('cp-grain-sample-loaded', 'true');
    }
  }
};
